version: "3"
services:
  workspace:
    build:
      context: .
    image: hook_crawler
    env_file:
      - .env
    ports:
      - 6800:6800
    volumes:
      - .:/workspace
    working_dir: /workspace
    stdin_open: true
    tty: true
  db:
    image: postgres:13.1
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DATABASE}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
